# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anamenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnaMenu(object):
    def setupUi(self, AnaMenu):
        AnaMenu.setObjectName("AnaMenu")
        AnaMenu.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(AnaMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(310, 140, 95, 135))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.quizBtn = QtWidgets.QPushButton(self.widget)
        self.quizBtn.setObjectName("quizBtn")
        self.verticalLayout.addWidget(self.quizBtn)
        self.keliimeEkleBtn = QtWidgets.QPushButton(self.widget)
        self.keliimeEkleBtn.setObjectName("keliimeEkleBtn")
        self.verticalLayout.addWidget(self.keliimeEkleBtn)
        self.ayarlarBtn = QtWidgets.QPushButton(self.widget)
        self.ayarlarBtn.setObjectName("ayarlarBtn")
        self.verticalLayout.addWidget(self.ayarlarBtn)
        self.cikisBtn = QtWidgets.QPushButton(self.widget)
        self.cikisBtn.setObjectName("cikisBtn")
        self.verticalLayout.addWidget(self.cikisBtn)
        AnaMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AnaMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        AnaMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AnaMenu)
        self.statusbar.setObjectName("statusbar")
        AnaMenu.setStatusBar(self.statusbar)

        self.retranslateUi(AnaMenu)
        QtCore.QMetaObject.connectSlotsByName(AnaMenu)

    def retranslateUi(self, AnaMenu):
        _translate = QtCore.QCoreApplication.translate
        AnaMenu.setWindowTitle(_translate("AnaMenu", "Ana Menü"))
        self.quizBtn.setText(_translate("AnaMenu", "Quiz"))
        self.keliimeEkleBtn.setText(_translate("AnaMenu", "Kelime Ekle"))
        self.ayarlarBtn.setText(_translate("AnaMenu", "Ayarlar"))
        self.cikisBtn.setText(_translate("AnaMenu", "Çıkış Yap"))
