# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ayarlar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ayarlar(object):
    def setupUi(self, ayarlar):
        ayarlar.setObjectName("ayarlar")
        ayarlar.resize(800, 600)
        ayarlar.setStyleSheet("background-color: #2c3e50;")

        self.centralwidget = QtWidgets.QWidget(ayarlar)
        self.centralwidget.setObjectName("centralwidget")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(290, 220, 223, 30))
        self.widget.setObjectName("widget")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.label.setStyleSheet("color: #ecf0f1; font-size: 14px;")
        self.horizontalLayout.addWidget(self.label)

        self.kacSoruBox = QtWidgets.QSpinBox(self.widget)
        self.kacSoruBox.setObjectName("kacSoruBox")
        self.kacSoruBox.setStyleSheet("background-color: #ecf0f1; padding: 5px;")
        self.horizontalLayout.addWidget(self.kacSoruBox)

        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(290, 260, 223, 40))
        self.widget1.setObjectName("widget1")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.geriDonBtn = QtWidgets.QPushButton(self.widget1)
        self.geriDonBtn.setObjectName("geriDonBtn")
        self.geriDonBtn.setStyleSheet("background-color: #e67e22; color: #ecf0f1; padding: 10px; font-size: 14px;")
        self.horizontalLayout_2.addWidget(self.geriDonBtn)

        self.kaydetBtn = QtWidgets.QPushButton(self.widget1)
        self.kaydetBtn.setObjectName("kaydetBtn")
        self.kaydetBtn.setStyleSheet("background-color: #27ae60; color: #ecf0f1; padding: 10px; font-size: 14px;")
        self.horizontalLayout_2.addWidget(self.kaydetBtn)

        ayarlar.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(ayarlar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        ayarlar.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(ayarlar)
        self.statusbar.setObjectName("statusbar")
        ayarlar.setStatusBar(self.statusbar)

        self.retranslateUi(ayarlar)
        QtCore.QMetaObject.connectSlotsByName(ayarlar)

    def retranslateUi(self, ayarlar):
        _translate = QtCore.QCoreApplication.translate
        ayarlar.setWindowTitle(_translate("ayarlar", "Ayarlar"))
        self.label.setText(_translate("ayarlar", "Kaç adet yeni kelime sorulsun:"))
        self.geriDonBtn.setText(_translate("ayarlar", "Geri Dön"))
        self.kaydetBtn.setText(_translate("ayarlar", "Kaydet"))


