# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kelimeEkle.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_KelimeEkleme(object):
    def setupUi(self, KelimeEkleme):
        KelimeEkleme.setObjectName("KelimeEkleme")
        KelimeEkleme.resize(800, 605)
        KelimeEkleme.setStyleSheet("background-color: #34495e;")
        
        self.centralwidget = QtWidgets.QWidget(KelimeEkleme)
        self.centralwidget.setObjectName("centralwidget")
        
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(260, 100, 258, 318))
        self.layoutWidget.setObjectName("layoutWidget")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.kelimeLne = QtWidgets.QLineEdit(self.layoutWidget)
        self.kelimeLne.setObjectName("kelimeLne")
        self.kelimeLne.setStyleSheet("background-color: #ecf0f1; padding: 5px;")
        self.verticalLayout.addWidget(self.kelimeLne)
        
        self.kelimeTrLne = QtWidgets.QLineEdit(self.layoutWidget)
        self.kelimeTrLne.setObjectName("kelimeTrLne")
        self.kelimeTrLne.setStyleSheet("background-color: #ecf0f1; padding: 5px;")
        self.verticalLayout.addWidget(self.kelimeTrLne)
        
        self.kelimeCumleTxt = QtWidgets.QTextEdit(self.layoutWidget)
        self.kelimeCumleTxt.setObjectName("kelimeCumleTxt")
        self.kelimeCumleTxt.setStyleSheet("background-color: #ecf0f1; padding: 5px;")
        self.verticalLayout.addWidget(self.kelimeCumleTxt)
        
        self.gorselBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.gorselBtn.setObjectName("gorselBtn")
        self.gorselBtn.setStyleSheet("background-color: #e67e22; color: #ecf0f1; padding: 10px; font-size: 14px;")
        self.verticalLayout.addWidget(self.gorselBtn)
        
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.geriDonBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.geriDonBtn.setObjectName("geriDonBtn")
        self.geriDonBtn.setStyleSheet("background-color: #e74c3c; color: #ecf0f1; padding: 10px; font-size: 14px;")
        self.horizontalLayout.addWidget(self.geriDonBtn)
        
        self.kelimeEkleBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.kelimeEkleBtn.setObjectName("kelimeEkleBtn")
        self.kelimeEkleBtn.setStyleSheet("background-color: #27ae60; color: #ecf0f1; padding: 10px; font-size: 14px;")
        self.horizontalLayout.addWidget(self.kelimeEkleBtn)
        
        self.verticalLayout.addLayout(self.horizontalLayout)
        
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 100, 251, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label.setStyleSheet("color: #ecf0f1; font-size: 14px;")
        self.verticalLayout_2.addWidget(self.label)
        
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("color: #ecf0f1; font-size: 14px;")
        self.verticalLayout_2.addWidget(self.label_2)
        
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_3.setStyleSheet("color: #ecf0f1; font-size: 14px;")
        self.verticalLayout_2.addWidget(self.label_3)
        
        KelimeEkleme.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(KelimeEkleme)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        KelimeEkleme.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(KelimeEkleme)
        self.statusbar.setObjectName("statusbar")
        KelimeEkleme.setStatusBar(self.statusbar)

        self.retranslateUi(KelimeEkleme)
        QtCore.QMetaObject.connectSlotsByName(KelimeEkleme)

    def retranslateUi(self, KelimeEkleme):
        _translate = QtCore.QCoreApplication.translate
        KelimeEkleme.setWindowTitle(_translate("KelimeEkleme", "Kelime Ekleme"))
        self.gorselBtn.setText(_translate("KelimeEkleme", "Görsel Ekle"))
        self.geriDonBtn.setText(_translate("KelimeEkleme", "Geri Dön"))
        self.kelimeEkleBtn.setText(_translate("KelimeEkleme", "Kelime Ekle"))
        self.label.setText(_translate("KelimeEkleme", "Kelime Giriniz:"))
        self.label_2.setText(_translate("KelimeEkleme", "Kelimenin Türkçesini Giriniz:"))
        self.label_3.setText(_translate("KelimeEkleme", "Kelimeyi Cümle İçersinde Kullanınız"))

