# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sifremiunuttum.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SifremiUnuttum(object):
    def setupUi(self, SifremiUnuttum):
        SifremiUnuttum.setObjectName("SifremiUnuttum")
        SifremiUnuttum.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SifremiUnuttum)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 140, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 210, 191, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 240, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 260, 171, 16))
        self.label_4.setObjectName("label_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(250, 140, 139, 181))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.epostaLne = QtWidgets.QLineEdit(self.widget)
        self.epostaLne.setObjectName("epostaLne")
        self.verticalLayout.addWidget(self.epostaLne)
        self.kodYollaBtn = QtWidgets.QPushButton(self.widget)
        self.kodYollaBtn.setObjectName("kodYollaBtn")
        self.verticalLayout.addWidget(self.kodYollaBtn)
        self.kodLne = QtWidgets.QLineEdit(self.widget)
        self.kodLne.setObjectName("kodLne")
        self.verticalLayout.addWidget(self.kodLne)
        self.yeniSifreLne = QtWidgets.QLineEdit(self.widget)
        self.yeniSifreLne.setObjectName("yeniSifreLne")
        self.verticalLayout.addWidget(self.yeniSifreLne)
        self.yeniSifreLne2 = QtWidgets.QLineEdit(self.widget)
        self.yeniSifreLne2.setObjectName("yeniSifreLne2")
        self.verticalLayout.addWidget(self.yeniSifreLne2)
        self.sifremiDegistirBtn = QtWidgets.QPushButton(self.widget)
        self.sifremiDegistirBtn.setObjectName("sifremiDegistirBtn")
        self.verticalLayout.addWidget(self.sifremiDegistirBtn)
        SifremiUnuttum.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SifremiUnuttum)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        SifremiUnuttum.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SifremiUnuttum)
        self.statusbar.setObjectName("statusbar")
        SifremiUnuttum.setStatusBar(self.statusbar)

        self.retranslateUi(SifremiUnuttum)
        QtCore.QMetaObject.connectSlotsByName(SifremiUnuttum)

    def retranslateUi(self, SifremiUnuttum):
        _translate = QtCore.QCoreApplication.translate
        SifremiUnuttum.setWindowTitle(_translate("SifremiUnuttum", "Şifremi Unuttum"))
        self.label.setText(_translate("SifremiUnuttum", "E-Postanızı Giriniz:"))
        self.label_2.setText(_translate("SifremiUnuttum", "E-Postanıza Gelen Kodu Giriniz:"))
        self.label_3.setText(_translate("SifremiUnuttum", "Yeni Şifrenizi Giriniz:"))
        self.label_4.setText(_translate("SifremiUnuttum", "Yeni Şifrenizi Yeniden Giriniz:"))
        self.kodYollaBtn.setText(_translate("SifremiUnuttum", "Kod Yolla"))
        self.sifremiDegistirBtn.setText(_translate("SifremiUnuttum", "Şifreni Değiştir"))
